package com.hankyong.hankyongsample.network

//Todo 수업 샘플에 사용한 공공 api 의 정보.
// https://data.seoul.go.kr/dataList/OA-13341/A/1/datasetView.do;jsessionid=5ECE4EACF05F7A04DDAD4AB3D06E3B13.new_portal-svr-21
// 공공 api 상세 스펙과 명세는 위 사이트에서 확인.


//Comm 공공 api 요청 성공 시 응답 데이터 샘플.
/*
{
  "GetJobInfo":{
    "list_total_count":2856,
    "RESULT":{
      "CODE":"INFO-000",
      "MESSAGE":"정상 처리되었습니다"
    },
    "row":[
      {
        "JO_REQST_NO":"J002202312270001",
        "JO_REGIST_NO":"DdA0022312272005",
        "CMPNY_NM":"선재어린이집",
        "BSNS_SUMRY_CN":"어린이집",
        "RCRIT_JSSFC_CMMN_CODE_SE":"215302",
        "JOBCODE_NM":"보육시설 서비스 종사원",
        "RCRIT_NMPR_CO":1.0,
        "ACDMCR_CMMN_CODE_SE":"J00100",
        "ACDMCR_NM":"관계없음",
        "EMPLYM_STLE_CMMN_CODE_SE":"J01101",
        "EMPLYM_STLE_CMMN_MM":"상용직",
        "WORK_PARAR_BASS_ADRES_CN":"서울 종로구수송동",
        "SUBWAY_NM":"",
        "DTY_CN":"&lt;국공립 선재어린이집 보육도우미 채용 공고&gt;\r\n\r\n□ 채용분야 : 보육도우미\r\n□ 직무내용 : 주방 도우미 및 청결 지원\r\n□ 근무시간 : 09:30~14:00 (1일 4시간, 주5일 근무/휴게시간 30분 포함) \r\n□ 급여조건 : 2023년 보육사업지침 인건비지급기준 준용(1,011,000원)_2024년도에  2024년 보육사업지침 인건비지급기준 적용예정\r\n□ 접수방법 : e-mail 접수(sjdaycare19@naver.com) / (제목)보육도우미 000으로 하나의 파일로 접수\r\n□ 제출서류 : 이력서(최근사진첨부,연락처 기재), 자기소개서, 자격증사본, 경력증명서(경력자에 한함), 개인정보 수집 및 이용 동의서(서류접수시 메일로 발송) \r\n□ 전형절차 : 1차 서류전형 후 2차 면접자는 개별통보\r\n□ 문의사항 : 기타 문의사항은 선재어린이집(02-720-9770)으로 문의해 주시기 바랍니다.\r\n□ 교통편 : 지하철 1호선 종각역 2번 출구에서 도보 10분 소요\r\n\r\n※ 시설현황 : 원아 71명, 교직원 18명",
        "CAREER_CND_CMMN_CODE_SE":"J01300",
        "CAREER_CND_NM":"무관",
        "HOPE_WAGE":"월급 / 101만원 ",
        "RET_GRANTS_NM":"퇴직연금",
        "WORK_TIME_NM":"09:30~14:00",
        "WORK_TM_NM":"주간",
        "HOLIDAY_NM":"주5일근무",
        "WEEK_WORK_HR":"19",
        "JO_FEINSR_SBSCRB_NM":"국민연금 고용보험 산재보험 건강보험",
        "RCEPT_CLOS_NM":"마감일 (2024-02-26)",
        "RCEPT_MTH_IEM_NM":"",
        "MODEL_MTH_NM":"서류  면접   ",
        "RCEPT_MTH_NM":"기타   ",
        "PRESENTN_PAPERS_NM":"이력서 자기소개서  ",
        "MNGR_NM":"임우식",
        "MNGR_PHON_NO":"02-731-9520",
        "MNGR_INSTT_NM":"서울일자리센터 청년일자리센터",
        "BASS_ADRES_CN":"서울특별시 종로구 우정국로 51 -4 (수송동) 수송동",
        "JO_SJ":"(종로구 수송동) 국공립 선재어린이집 주방도우미 채용",
        "JO_REG_DT":"2023-12-27",
        "GUI_LN":"(월급)101만원 / 서울 종로구 / 경력 무관"
      },
      {
        "JO_REQST_NO":"J501202312270001",
        "JO_REGIST_NO":"DdA5012312272002",
        "CMPNY_NM":"주식회사 유알피",
        "BSNS_SUMRY_CN":"소프트웨어개발, 서버관리및유지보수, 연구개발업",
        "RCRIT_JSSFC_CMMN_CODE_SE":"531700",
        "JOBCODE_NM":"음료 조리사(바리스타 포함)",
        "RCRIT_NMPR_CO":1.0,
        "ACDMCR_CMMN_CODE_SE":"J00100",
        "ACDMCR_NM":"관계없음",
        "EMPLYM_STLE_CMMN_CODE_SE":"J01105",
        "EMPLYM_STLE_CMMN_MM":"상용직(시간제)",
        "WORK_PARAR_BASS_ADRES_CN":"서울 강서구NH서울타워 5층 (주)유알피",
        "SUBWAY_NM":"증미",
        "DTY_CN":"08:30~13:00 오전(오픈) / 13:00~17:00 오후(마감)  \r\n2교대 사내카페 바리스타 \r\n장애인(청각) 우대",
        "CAREER_CND_CMMN_CODE_SE":"J01300",
        "CAREER_CND_NM":"무관",
        "HOPE_WAGE":"시급 / 9860원 - 면접 후 협의가능 ",
        "RET_GRANTS_NM":"퇴직금",
        "WORK_TIME_NM":"08:30~13:00, 13:00~17:00",
        "WORK_TM_NM":"2교대",
        "HOLIDAY_NM":"주5일근무",
        "WEEK_WORK_HR":"20",
        "JO_FEINSR_SBSCRB_NM":"국민연금 고용보험 산재보험 건강보험",
        "RCEPT_CLOS_NM":"마감일 (2024-02-26)",
        "RCEPT_MTH_IEM_NM":"서울특별시 강서구 양천로 570  (등촌동) NH서울타워 5층 (주)유알피",
        "MODEL_MTH_NM":"서류  면접   ",
        "RCEPT_MTH_NM":"온라인 전자우편  ",
        "PRESENTN_PAPERS_NM":"이력서 자기소개서  ",
        "MNGR_NM":"김정",
        "MNGR_PHON_NO":"070-4827-1629",
        "MNGR_INSTT_NM":"서울시장애인일자리통합지원센터",
        "BASS_ADRES_CN":"서울특별시 강서구 양천로 570  (등촌동) NH서울타워 5층 (주)유알피",
        "JO_SJ":"사내카페 바리스타 채용",
        "JO_REG_DT":"2023-12-27",
        "GUI_LN":"(시급)9860원 / 서울 강서구 / 경력 무관"
      },
      {
        "JO_REQST_NO":"J322202312200003",
        "JO_REGIST_NO":"DdA3222312202035",
        "CMPNY_NM":"한전FMS주식회사",
        "BSNS_SUMRY_CN":"한전 사옥 관리(청소·시설관리·경비) 서비스",
        "RCRIT_JSSFC_CMMN_CODE_SE":"029104",
        "JOBCODE_NM":"데스크 안내원",
        "RCRIT_NMPR_CO":1.0,
        "ACDMCR_CMMN_CODE_SE":"J00100",
        "ACDMCR_NM":"관계없음",
        "EMPLYM_STLE_CMMN_CODE_SE":"J01102",
        "EMPLYM_STLE_CMMN_MM":"계약직",
        "WORK_PARAR_BASS_ADRES_CN":"서울 서초구.",
        "SUBWAY_NM":"양재",
        "DTY_CN":"[담당업무]\r\n -한전아트센터 사옥 내 안내데스크 등 기타경비 업무\r\n (근무지 : 서울시 서초구 효령로 72길 60, 한전아트센터 한전FMS(주)\r\n\r\n[자격요건]\r\n -경력 : 무관\r\n\r\n[근무조건]\r\n -계약기간: 계약직 (~2024.12.31.)\r\n -근무형태: 주5일 (월~금,08:30~17:30)\r\n -급여: 월 230여만원(세전)\r\n\r\n*팩스지원시 &quot;한전아트센터 안내데스크 지원&quot; 기재 필수.",
        "CAREER_CND_CMMN_CODE_SE":"J01300",
        "CAREER_CND_NM":"무관",
        "HOPE_WAGE":"월급 / 230만원 ",
        "RET_GRANTS_NM":"해당없음",
        "WORK_TIME_NM":"08:30~17:30 (휴게 1시간)",
        "WORK_TM_NM":"주간",
        "HOLIDAY_NM":"주5일근무",
        "WEEK_WORK_HR":"40",
        "JO_FEINSR_SBSCRB_NM":"국민연금 고용보험 산재보험 건강보험",
        "RCEPT_CLOS_NM":"마감일 (2024-02-18)",
        "RCEPT_MTH_IEM_NM":"",
        "MODEL_MTH_NM":"서류  면접   ",
        "RCEPT_MTH_NM":"팩스 기타  ",
        "PRESENTN_PAPERS_NM":"이력서 자기소개서  ",
        "MNGR_NM":"고범석",
        "MNGR_PHON_NO":"02-2155-8768",
        "MNGR_INSTT_NM":"서초구",
        "BASS_ADRES_CN":"전라남도 나주시 상야1길 예가람타워 5층",
        "JO_SJ":"한전에프엠에스 한전아트센터 현관안내 계약직 채용",
        "JO_REG_DT":"2023-12-20",
        "GUI_LN":"(월급)230만원 / 서울 서초구 / 경력 무관"
      },
      {
        "JO_REQST_NO":"J301202312220004",
        "JO_REGIST_NO":"DdA3012312222022",
        "CMPNY_NM":"(주)두잉씨앤에스",
        "BSNS_SUMRY_CN":"서비스,유지,보수용역업",
        "RCRIT_JSSFC_CMMN_CODE_SE":"561101",
        "JOBCODE_NM":"건물 청소원(공공건물,아파트,사무실,병원,상가,공장 등)",
        "RCRIT_NMPR_CO":1.0,
        "ACDMCR_CMMN_CODE_SE":"J00100",
        "ACDMCR_NM":"관계없음",
        "EMPLYM_STLE_CMMN_CODE_SE":"J01102",
        "EMPLYM_STLE_CMMN_MM":"계약직",
        "WORK_PARAR_BASS_ADRES_CN":"서울 서초구.",
        "SUBWAY_NM":"",
        "DTY_CN":"상가층 미화업무",
        "CAREER_CND_CMMN_CODE_SE":"J01300",
        "CAREER_CND_NM":"무관",
        "HOPE_WAGE":"월급 / 196만원 ",
        "RET_GRANTS_NM":"퇴직금",
        "WORK_TIME_NM":"07:00~16:00",
        "WORK_TM_NM":"주간",
        "HOLIDAY_NM":"기타(첫째, 셋째 일요일 휴무)",
        "WEEK_WORK_HR":"32",
        "JO_FEINSR_SBSCRB_NM":"국민연금 고용보험 산재보험 건강보험",
        "RCEPT_CLOS_NM":"마감일 (2024-02-17)",
        "RCEPT_MTH_IEM_NM":"",
        "MODEL_MTH_NM":"면접    ",
        "RCEPT_MTH_NM":"방문 팩스  ",
        "PRESENTN_PAPERS_NM":"이력서   ",
        "MNGR_NM":"김유진",
        "MNGR_PHON_NO":"02-2148-3958",
        "MNGR_INSTT_NM":"종로구",
        "BASS_ADRES_CN":"경기도 성남시 분당구 판교역로 231  (삼평동) 에스동 908호(삼평동,에이치스퀘어)",
        "JO_SJ":"상가 미화원",
        "JO_REG_DT":"2023-12-22",
        "GUI_LN":"(월급)196만원 / 서울 서초구 / 경력 무관"
      },
      {
        "JO_REQST_NO":"J318202312150001",
        "JO_REGIST_NO":"DdA3182312152035",
        "CMPNY_NM":"시흥동943번지 일원 LH참여형 가로주택정비사업조합",
        "BSNS_SUMRY_CN":"가로주택정비사업조합",
        "RCRIT_JSSFC_CMMN_CODE_SE":"029506",
        "JOBCODE_NM":"사무 보조원(일반사업체)",
        "RCRIT_NMPR_CO":1.0,
        "ACDMCR_CMMN_CODE_SE":"J00100",
        "ACDMCR_NM":"관계없음",
        "EMPLYM_STLE_CMMN_CODE_SE":"J01105",
        "EMPLYM_STLE_CMMN_MM":"상용직(시간제)",
        "WORK_PARAR_BASS_ADRES_CN":"서울 금천구2층",
        "SUBWAY_NM":"석수",
        "DTY_CN":"가로주택정비사업 조합 일반 행정, 사무 업무\r\n\r\n\r\n수습기간 2개월 있음.",
        "CAREER_CND_CMMN_CODE_SE":"J01300",
        "CAREER_CND_NM":"무관",
        "HOPE_WAGE":"최소연봉 / 3200만원 ",
        "RET_GRANTS_NM":"퇴직금",
        "WORK_TIME_NM":"09:00~18:00",
        "WORK_TM_NM":"주간",
        "HOLIDAY_NM":"주5일근무",
        "WEEK_WORK_HR":"40",
        "JO_FEINSR_SBSCRB_NM":"국민연금 고용보험 산재보험 건강보험",
        "RCEPT_CLOS_NM":"마감일 (2024-02-14)",
        "RCEPT_MTH_IEM_NM":"",
        "MODEL_MTH_NM":"   ",
        "RCEPT_MTH_NM":"온라인 전자우편  ",
        "PRESENTN_PAPERS_NM":"이력서 자기소개서  ",
        "MNGR_NM":"이수미",
        "MNGR_PHON_NO":"02-2627-1919",
        "MNGR_INSTT_NM":"금천구",
        "BASS_ADRES_CN":"서울특별시 금천구 시흥대로28길 47 -9 (시흥동) 2층",
        "JO_SJ":"[가로주택정비사업 조합사무실] 일반 사무직 채용",
        "JO_REG_DT":"2023-12-15",
        "GUI_LN":"(연봉)3200만원 / 서울 금천구 / 경력 무관"
      }
    ]
  }
}
    */